#version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    volumes:
      - frontend_dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
      - VITE_TRANSLATE_API=http://libretranslate:5000/translate  # Internal Docker host
    depends_on:
      - libretranslate

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LANGUAGES=en,es,fr,de,pt
    command: ["--load-only", "en,es,de,pt,fr"]

volumes:
  frontend_dist:
