# Local override for development
#version: "3.8"

services:
  frontend:
    command: pnpm dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
