services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_TRANSLATE_API=http://localhost:5000/translate
    depends_on:
      - libretranslate

  libretranslate:
    build:
      context: .
      dockerfile: Dockerfile.libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_API_KEYS=true
      - LT_API_KEYS_FILE=/app/api_keys.json
    volumes:
      - ./api_keys.json:/app/api_keys.json:ro
    command: >
      bash -c "
        libretranslate || (
          echo '[⚠] LibreTranslate failed to fetch models online. Falling back to offline models...' &&
          /app/venv/bin/python3 -m argostranslate.package install /opt/models/*.argosmodel &&
          libretranslate
        )
      "
