# Production Docker Compose
#version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: prod
    environment:
      - NODE_ENV=production
      - VITE_TRANSLATE_API=http://libretranslate:5000/translate
    volumes:
      - frontend_dist:/usr/share/nginx/html
    depends_on:
      libretranslate:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend

  libretranslate:
    image: argosopentech/libretranslate:latest
    ports:
      - "5000:5000"
    environment:
      - LANGUAGES=en,es,fr,de,pt
    command: ["--load-only", "en,es,fr,de,pt"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  frontend_dist:
