FROM libretranslate/libretranslate:latest

RUN mkdir -p /app/models

COPY ./argos-models-packages/*.argosmodel /app/models/
RUN /app/venv/bin/python3 -m argostranslate.package install /app/models/*.argosmodel

COPY ./entrypoint.sh /app/entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]
