services:
  frontend:
    build:
      context: .
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"
    depends_on:
      - libretranslate
    command: |
      sh -c "npm run build && cp -r dist/* /usr/share/nginx/html && nginx -g 'daemon off;'"

  libretranslate:
    image: libretranslate/libretranslate
    ports:
      - "5000:5000"
    environment:
      - LANGUAGES=en,es,fr,de,pt
